version: '3.7'

services:
  go-db:
    container_name: go-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-app:
    container_name: go-app
    image: juliocesar014/authapiuser:latest
    build: .
    environment:
      DATABASE_URL: "host=go-db user=postgres password=postgres dbname=users sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go-db
    restart: on-failure:10
volumes:  
  pgdata: {}